from typing import Protocol

from sentinel.schemas.moderation import ModerationJob, ModerationRequest, StoredModerationJob


class JobStore(Protocol):
    def create(self, stored_job: StoredModerationJob) -> bool: ...

    def get(self, job_id: str) -> StoredModerationJob | None: ...

    def save(self, stored_job: StoredModerationJob) -> None: ...

    def close(self) -> None: ...


class EventPublisher(Protocol):
    def publish(self, topic: str, key: str, payload: bytes) -> None: ...

    def close(self) -> None: ...


class JobService(Protocol):
    def submit(self, request: ModerationRequest) -> ModerationJob: ...

    def get(self, job_id: str) -> ModerationJob | None: ...

    def close(self) -> None: ...
